const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "PC Gamer Intel I7",
      price: 1000,
      image: require("../src/imagenes/imgdat/compugamer.jpg"),
      category: "PC",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Auriculares gamer Redragon",
      price: 200,
      image: require("../src/imagenes/imgdat/auricularesgamrredragon.jpg"),
      category: "Periférico",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Celular Gamer",
      price: 600,
      image: require("../src/imagenes/imgdat/celulargamer.jpg"),
      category: "Celular",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Monitor 144hz",
      price: 500,
      image: require("../src/imagenes/imgdat/monitor144hz.jpg"),
      category: "Monitor",
      cantidad: 1,
    },
    {
      id: 5,
      title: "Escritorio Gamer",
      price: 200,
      image: require("../src/imagenes/imgdat/escritoriogamer.jpg"),
      category: "muebles",
      cantidad: 1,
    },
    {
      id: 7,
      title: "Pc Gamer Ryzen 7",
      price: 700,
      image: require("../src/imagenes/imgdat/pcgamer.jpg"),
      category: "PC",
      cantidad: 1,
    },
    {
      id: 8,
      title: "Reloj Fit Samsung",
      price: 300,
      image: require("../src/imagenes/imgdat/relofit.jpg"),
      category: "reloj",
      cantidad: 1,
    },
    {
      id: 9,
      title: "Refrigeracion Liquida",
      price: 650,
      image: require("../src/imagenes/imgdat/refrigeracionliquida.jpg"),
      category: "Refrigeracion",
      cantidad: 1,
    },
    {
      id: 10,
      title: "Reloj Samsung",
      price: 500,
      image: require("../src/imagenes/imgdat/reloj-samung.jpg"),
      category: "nike",
      cantidad: 1,
    },
    {
      id: 11,
      title: "Remera",
      price: 150,
      image: require("../src/imagenes/imgdat/remeragamer.jpg"),
      category: "Ropa",
      cantidad: 1,
    },
  ],
};

export default data;
