const data = {
  status: "success",
  items: [
    {
      id: 1,
      title: "PC Gamer",
      price: 1000,
      image: require("../src/imagenes/pcgamer.svg"),
      category: "PC",
      cantidad: 1,
    },
    {
      id: 2,
      title: "Auriculares gamer Redragon",
      price: 200,
      image: require("../src/imagenes/auricularesgamrredragon.svg"),
      category: "Periférico",
      cantidad: 1,
    },
    {
      id: 3,
      title: "Celular Gamer",
      price: 600,
      image: require("../src/imagenes/celulargamer.svg"),
      category: "Celular",
      cantidad: 1,
    },
    {
      id: 4,
      title: "Monitor 144hz",
      price: 500,
      image: require("../src/imagenes/monitor144hz.svg"),
      category: "Monitor",
      cantidad: 1,
    },
    {
      id: 5,
      title: "Escritorio Gamer",
      price: 200,
      image: require("../src/imagenes/escritoriogamer.svg"),
      category: "muebles",
      cantidad: 1,
    },
    {
      id: 7,
      title: "Nootbook Gamer",
      price: 700,
      image: require("../src/imagenes/compugamer.svg"),
      category: "Nootbook",
      cantidad: 1,
    },
    {
      id: 8,
      title: "Reloj Fit Samsung",
      price: 300,
      image: require("../src/imagenes/relofit.svg"),
      category: "reloj",
      cantidad: 1,
    },
    {
      id: 9,
      title: "Refrigeracion Liquida",
      price: 650,
      image: require("../src/imagenes/refrigeracionliquida.svg"),
      category: "Refrigeracion",
      cantidad: 1,
    },
    {
      id: 10,
      title: "Reloj Samsung",
      price: 500,
      image: require("../src/imagenes/reloj samung.svg"),
      category: "nike",
      cantidad: 1,
    },
    {
      id: 11,
      title: "Remera",
      price: 150,
      image: require("../src/imagenes/remeragamer.svg"),
      category: "Ropa",
      cantidad: 1,
    },
  ],
};

export default data;
